### ISSUE TITLE
How to run the examples?

### ISSUE THREAD

**Issue by keem-younghan** [ctu-mrs/octomap_mapping_planning#6]
Hi, I'm trying to run the examples on Singularity environment.

I've tried by running these script in different shells.

```
[MRS Singularity] n@pc:~/user_ros_workspace/src/octomap_mapping_planning/tmux/simulation_example$ ./start.sh 
[MRS Singularity] n@pc:~/user_ros_workspace/src/octomap_mapping_planning/tmux/uav_aloam_example$ ./tmux.sh 
```
But the drone doesn't fly after running tmux.sh. Is there any problem in my procedure? Thanks.

**Comment by klaxalk** [comment]
Sorry, I had a compatibility issue between our packages. If you wait till tomorrow, the new Singularity build will be ok. Then run the "simulation_session".

**Comment by keem-younghan** [comment]
Thanks for checking!

**Comment by klaxalk** [comment]
Hey, I checked it today with fresh Singularity image, and it works.

**Comment by keem-younghan** [comment]
Tried too, it worked on my env. Thanks!
