### ISSUE TITLE
lose the function of obstacle avoidance

### ISSUE THREAD

**Issue by donglianghere** [ctu-mrs/octomap_mapping_planning#7]
@klaxalk when i run the example in dir "octomap_mapping_planning/tmux/simulation_example" with the command ./start.sh, i find the program does not have the function of obstacle avoidance, and the planned path direct straight to the goal, Why? Thanks!

**Comment by donglianghere** [comment]
[2022-08-29 22-21-57.zip](https://github.com/ctu-mrs/octomap_mapping_planning/files/9445355/2022-08-29.22-21-57.zip)
Here is the video

**Comment by donglianghere** [comment]
file session.yml
name: simulation
root: ./
startup_window: mapplan
pre_window: export UAV_NAME=uav1; export RUN_TYPE=simulation; export UAV_TYPE=t650; export SENSORS="garmin_down"; export WORLD_FILE=./custom_configs/world.yaml; export ODOMETRY_TYPE="gps"
windows:
  - roscore:
      layout: tiled
      panes:
        - roscore
  - gazebo:
      layout: tiled
      panes:
        - waitForRos; roslaunch mrs_simulation simulation.launch world_name:=forest gui:=true
        - waitForOdometry; gz camera -c gzclient_camera -f uav1; history -s gz camera -c gzclient_camera -f uav1
  - status:
      layout: tiled
      panes:
        - waitForSimulation; roslaunch mrs_uav_status status.launch
  - spawn:
      layout: tiled
      panes:
        #- waitForSimulation; rosservice call /mrs_drone_spawner/spawn "1 $UAV_TYPE --enable-rangefinder --enable-ouster --ouster-model OS0-128 --use-gpu-ray --pos 0 0 1.0 0"
        # - waitForSimulation; rosservice call /mrs_drone_spawner/spawn "1 $UAV_TYPE --enable-rangefinder --use-gpu-ray --enable-realsense-down --enable-realsense-front --pos 0 0 1.0 0 "
        - waitForSimulation; rosservice call /mrs_drone_spawner/spawn "1 $UAV_TYPE --enable-rangefinder --enable-realsense-down --enable-realsense-front --enable-ouster --ouster-model OS0-128 --use-gpu-ray --pos 0 0 1.0 0"
  - control:
       layout: tiled
       panes:
         - waitForOdometry; roslaunch mrs_uav_general core.launch config_odometry:=./custom_configs/odometry.yaml config_constraint_manager:=./custom_configs/constraint_manager.yaml
  - mapplan:
      layout: tiled
      panes:
        - waitForOdometry; roslaunch octomap_mapping_planning mapplan.launch config_octomap:=./custom_configs/octomap.yaml config_pcl_filter_ouster:=./custom_configs/ouster_filter_mapping.yaml config_pathfinder:=./custom_configs/pathfinder.yaml config_trajectory_generation:=./custom_configs/trajectory_generation.yaml config_pcl_filter_rs_front:=./custom_configs/rs_front_filter.yaml config_pcl_filter_rs_down:=./custom_configs/rs_down_filter.yaml
  - map:
      layout: tiled
      panes:
        - 'history -s rosservice call /uav1/octomap_server/save_map example'
        - 'history -s rosservice call /uav1/octomap_server/load_map example'
  - goto:
      layout: tiled
      panes:
        - 'history -s rosservice call /$UAV_NAME/pathfinder/goto \"goal: \[60.0, 0.0, 2.5, 0.0\]\";
           history -s rosservice call /$UAV_NAME/pathfinder/goto \"goal: \[-60.0, 0.0, 2.5, 0.0\]\"'
  - takeoff:
      layout: tiled
      panes:
        - waitForSimulation; roslaunch mrs_uav_general automatic_start.launch
        - 'waitForControl;
          rosservice call /$UAV_NAME/mavros/cmd/arming 1;
          sleep 2;
          rosservice call /$UAV_NAME/mavros/set_mode 0 offboard'
  - rviz:
      layout: tiled
      panes:
        - waitForControl; rosrun rviz rviz -d ./rviz.rviz
        - waitForControl; roslaunch mrs_rviz_plugins load_robot.launch
  - easy_control:
      layout: tiled
      panes:
        - waitForControl; waitForControl; roslaunch mrs_uav_general logitech_joystick.launch
        - waitForControl; waitForControl; roslaunch mrs_rviz_plugins rviz_interface.launch
  - layout:
      layout: tiled
      panes:
        - waitForControl; sleep 3; ~/.i3/layout_manager.sh ./layout.json

**Comment by donglianghere** [comment]
@spurnvoj @penickar Hi, could you please help me with this issue?

**Comment by klaxalk** [comment]
Hey, the collision avoidance / planning never got lost. The "Nav goal" you issued from Rviz never work that way. It generates a reference command directly for the ControlManager. That is on a much lower level than with this planning + mapping package. To issue a command for the planner, please use the `/uav*/pathfinder/goto` or `/uav*/pathfinder/referece` services. One is prepared in the tmux session, if you scroll right few times.

**Comment by klaxalk** [comment]
... since you posted it above yourself:

>     * goto:
>       layout: tiled
>       panes:
>       - 'history -s rosservice call /$UAV_NAME/pathfinder/goto "goal: [60.0, 0.0, 2.5, 0.0]";
>       history -s rosservice call /$UAV_NAME/pathfinder/goto "goal: [-60.0, 0.0, 2.5, 0.0]"'

**Comment by donglianghere** [comment]
The simulation is perfect! @klaxalk  Thanks a lot!
